#!/usr/bin/env python3

import os
import sys
import requests
from lkv373a import cgi

if len(sys.argv) != 3:
  print('{} HOST FILE'.format(os.path.basename(__file__)))
  sys.exit(1)

cgi.upgrade_encoder(sys.argv[1], sys.argv[2])
