#!/usr/bin/env python3

import asyncio
import async_timeout
import os
import sys
from lkv373a import cgi

if len(sys.argv) != 3:
  print('{} HOST FILE'.format(os.path.basename(__file__)))
  sys.exit(1)

async def do_upgrade():
  async with async_timeout.timeout(30):
    await cgi.upgrade_encoder(sys.argv[1], sys.argv[2])

asyncio.run(do_upgrade())
