#!/usr/bin/env python3

import sys
from lkv373a import vserprog

def usage():
  print(
    "{0} - Lists devices\n"
    "{0} ID - Finds the tty of a given device\n".format(sys.argv[0]))

ids = ['mu1', 'u2']
vserprogs = vserprog.list_vserprogs()

if len(sys.argv) == 1:
  for serprog in ids:
    print('%04s: %s' % (serprog.upper(), vserprogs.get(serprog, '-')))
elif len(sys.argv) == 2:
  ident = sys.argv[1].lower()
  try:
    print(vserprogs[ident])
  except KeyError:
    sys.stderr.write("vserprog '%s' not found\n" % ident)
    sys.exit(1)
else:
  usage()
