#!/usr/bin/env python3

import lkv373a
import serial
import sys

if not lkv373a.tty_device:
  sys.stderr.write('Serial device not found\n')
  sys.exit(1)

with serial.Serial('/dev/{}'.format(lkv373a.tty_device), 115200) as ser:
  while True:
    sys.stdout.write(ser.readline().decode('ascii', 'ignore'))
