#!/usr/bin/env python3

from lkv373a import vserprog

vserprog_devices = vserprog.devices.values()
print('Tristating {}'.format(', '.join(vserprog_devices)))
vserprog.trisate_vserprogs(vserprog_devices)
